#! /usr/bin/env zsh

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
# yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                float
yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0.0
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

yabai -m config window_border                on
yabai -m config window_border_width          1
# yabai -m config active_window_border_color   0xff775759
# yabai -m config active_window_border_color   0xff5BB33C
# yabai -m config active_window_border_color   0xffB16286
# yabai -m config active_window_border_color   0xff689d6a
yabai -m config active_window_border_color   0xffa89984
yabai -m config normal_window_border_color   0xff282828
# yabai -m config insert_window_border_color   0xffd75f5f


# general space settings
yabai -m config layout                       bsp

# for spacebar or any other bar if needed
# yabai -m config top_padding                  28
yabai -m config top_padding                  20

yabai -m config top_padding                  3
yabai -m config bottom_padding               3
yabai -m config left_padding                 3
yabai -m config right_padding                3
yabai -m config window_gap                   3

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Meeter$" manage=off
yabai -m rule --add app="^Snipaste$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Firefox$" space=^1
yabai -m rule --add app="^Emacs$" manage=on
yabai -m rule --add app="^mpv$" manage=off
yabai -m rule --add app="^VOX$" manage=off
yabai -m rule --add app="^Steam$" manage=off
yabai -m rule --add app="^DeepL$" manage=off
yabai -m rule --add app="^1Password 7$" manage=off
yabai -m rule --add app="^ScreenBrush$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^Hue Sync$" manage=off
yabai -m rule --add app="^MenuBar Stats$" manage=off
yabai -m rule --add app="^iGlance$" manage=off
yabai -m rule --add app="^ObinsKit$" manage=off
yabai -m rule --add app="^OS X Color Panel$" manage=off
yabai -m rule --add app="^Digital Colour Meter$" manage=off
# yabai -m rule --add app="^Lunar$" manage=off
# yabai -m rule --add app="^zoom.us$" manage=off

yabai -m rule --add title="zoom floating video window" manage=off
yabai -m rule --add title="zoom share statusbar window" manage=off
yabai -m rule --add title="Microsoft Teams Notification" manage=off
yabai -m rule --add title="Microsoft Teams Call in progress Meeting*." manage=off

yabai -m rule --add title="zoom floating video window" mouse_follows_focus=off
yabai -m rule --add title="zoom share*." mouse_follows_focus=off
yabai -m rule --add title="Microsoft Teams Notification" mouse_follows_focus=off
yabai -m rule --add title="Microsoft Teams Call*." mouse_follows_focus=off


# yabai -m rule --add app="^IntelliJ IDEA$" manage=off
# yabai -m rule --add app="^IntelliJ IDEA$" title="/Users/amansour/porsche/git/pos/" manage=on
# yabai -m rule --add app="^IntelliJ IDEA$" manage=off
yabai -m rule --add title='.*Welcome*.|Checkout*.|.*Configurations|Choose*.|Import*.|.*Charges|Tip*.|Rename*.|IDE*.|Plugins|Create*.|Preferences|Delete|Breakout*.|Library*.|Tip.*|Merge.*|Conflicts|.*Changelist*.|Extract*.|Problems*.|Change*.' manage=off

# yabai -m rule --add app="^Discord$" grid=6:6:1:1:3:3 manage=off
# yabai -m rule --add app="^kitty$" space=^2
# yabai -m rule --add app="^Slack$" space=^4
# yabai -m rule --add title="^Zoom Meeting$" space=^3


# yabai -m signal --add event='space_changed' action="sh ~/.config/yabai/clean_empty_spaces.sh"

# If no window on the current space is focused after a window is destroyed or
# minimized, or an application is hidden, focus the window under the cursor.
yabai -m signal --add event='window_destroyed' action="~/.config/yabai/focus_under_mouse"
yabai -m signal --add event='window_minimized' action="~/.config/yabai/focus_under_mouse"
yabai -m signal --add event='application_hidden' action="~/.config/yabai/focus_under_mouse"
yabai -m signal --add event='space_changed' action="~/.config/yabai/focus_under_mouse"
yabai -m signal --add event='space_changed' action="~/.config/yabai/ignore_Teams"
yabai -m signal --add event='space_changed' action="~/.config/yabai/ignore_Zoom"

echo "yabai configuration loaded.."
