#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                float
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  28
yabai -m config bottom_padding               3
yabai -m config left_padding                 3
yabai -m config right_padding                3
yabai -m config window_gap                   3

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^CopyQ$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Firefox$" space=^1
yabai -m rule --add app="^Emacs$" manage=on
yabai -m rule --add app="^mpv$" manage=off
yabai -m rule --add app="^Steam$" space=7 manage=off

yabai -m rule --add app="^Discord$" space=7 grid=6:6:1:1:3:3
# yabai -m rule --add app="^kitty$" space=^2
# yabai -m rule --add app="^Slack$" space=^4
# yabai -m rule --add app="^zoom.us$" space=^3

# Stopped using ubersicht till the focus bug is gone. issue tracked.
# yabai -m signal --add event=window_focused \
#   action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-windows-primary-jsx\"'"
#
# yabai -m signal --add event=dock_did_restart \
#   action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-windows-primary-jsx\"'"
#
# yabai -m signal --add event=space_changed \
#   action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-windows-primary-jsx\"'"
#
# yabai -m signal --add event=window_moved \
#   action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-windows-primary-jsx\"'"

find "${TMPDIR}" -type f -perm +111 -name "yabai_${USER}_monocle_mode_*" -delete

echo "yabai configuration loaded.."
