require("plugins.nvimtree")
require("plugins.theme")
require("plugins.bufferline")
require("plugins.nerdcommenter")
require("plugins.sandwich")
require("plugins.compe")
require("plugins.galaxyline")
require("plugins.blank-line")
require("plugins.treesitter")
require("plugins.matchup")
require("plugins.autopairs")
require("plugins.lspfuzzy")
require("plugins.signs")
require("plugins.fzf")
-- require("plugins.neogit")
require("plugins.nvim-lint")
require("plugins.lastplace")
-- require("plugins.notational")
require("plugins.current-word")
require("plugins.formatter")
require("plugins.vimwiki")
