require("plugins.nvimtree")
require("plugins.theme")
require("plugins.bufferline")
require("plugins.nerdcommenter")
require("plugins.sandwich")
require("plugins.compe")
require("plugins.galaxyline")
require("plugins.blank-line")
require("plugins.treesitter")
require("plugins.matchup")
require("plugins.autopairs")
-- require("plugins.lspfuzzy")
require("plugins.signs")
require("plugins.fzf")
require("plugins.neogit")
require("plugins.lastplace")
require("plugins.current-word")
require("plugins.formatter")
require("plugins.vimwiki")
require("plugins.terraform")

-- require("navigator").setup()
-- require("plugins.nvim-lint")

require("hop").setup({ keys = "etovxqpdygfblzhckisuran" })
require("fzf_lsp").setup()
require("which-key").setup()
